### ISSUE TITLE
Disconnecting aircraft causes unchecked null value

### ISSUE THREAD

**Issue by daniele-athome** [daniele-athome/airborne#42]
```
[AppConfig] Selecting no aircraft

======== Exception caught by widgets library =======================================================
The following _CastError was thrown building Builder:
Null check operator used on a null value

The relevant error-causing widget was: 
  PlatformApp PlatformApp:file:///home/daniele/Development/flyroma/airborne-flutter/airborne/lib/main.dart:103:47
When the exception was thrown, this was the stack: 
#0      AppConfig.googleServiceAccountJson (package:airborne/helpers/config.dart:54:28)
#1      _MainNavigationState._rebuildServices (package:airborne/main.dart:190:34)
#2      _MainNavigationState.didUpdateWidget (package:airborne/main.dart:183:5)
#3      StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:57)
```

**Comment by daniele-athome** [comment]
Somewhat fixed in a27dc952402228eab2ad7c7b451f66dafaa9d0c2.
